<a href="https://colab.research.google.com/github/ga642381/ML2021-Spring/blob/main/Pytorch/Pytorch_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pytorch Tutorial**


## Basic Operation

In [14]:
import torch
import numpy as np

#### 1. Tensor -- Constructor

In [18]:
x = torch.tensor([[1,-1],[-1,1]])
y = torch.from_numpy(np.array([[1,-1],[-1,1]]))
z = torch.randn(3,4)
zero = torch.zeros(2,2) 
eye = torch.eye(3,3)

x,y,z,zero,eye

(tensor([[ 1, -1],
         [-1,  1]]),
 tensor([[ 1, -1],
         [-1,  1]]),
 tensor([[ 1.7527, -0.3258, -0.4806,  1.1229],
         [ 1.1349, -0.1111, -0.9191, -1.1412],
         [-0.2201, -0.8503, -0.7040,  0.3539]]),
 tensor([[0., 0.],
         [0., 0.]]),
 tensor([[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]))

#### 2. Tensor -- Operators

In [31]:
# Squeeze
x = torch.zeros(1,2,3)
print(x.shape)
x = x.squeeze(0)
print(x.shape)

# Unsqueeze
x = torch.eye(2,3)
x = x.unsqueeze(1)
print(x.shape)

torch.Size([1, 2, 3])
torch.Size([2, 3])
torch.Size([2, 1, 3])


In [12]:
# 1. max of entire tensor (torch.max(input) → Tensor)
m = torch.max(x)
print(m)

tensor(2.0846)


In [41]:
# Transpose
x = torch.zeros([2, 3])
x = x.transpose(0,1)
x.shape

torch.Size([3, 2])

In [48]:
# Cat: concatenate multiple tensors
x = torch.zeros(2,1,3)
y = torch.zeros(2,2,3)
z = torch.zeros(2,3,3)
w = torch.cat([x,y,z],dim= 1)
w.shape

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [71]:
# Addition
x = torch.randint(-1,1,(2,3))
y = torch.randint(-1,1,(2,3))
print(x)
print(y)
print(x + y)
# Subtraction
print(x - y)
# Power
print(x.pow(2))

tensor([[ 0, -1, -1],
        [-1, -1, -1],
        [ 0, -1,  0]])
tensor([[-1, -1,  0],
        [ 0,  0,  0]])


RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0

In [96]:
# Summation
x.sum()

# Mean
y = torch.tensor(x,dtype=float)
y.mean()

/tmp/ipykernel_13419/4015554638.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = torch.tensor(x,dtype=float)


tensor(-0.6667, dtype=torch.float64)

#### 3. Shape manipulation

In [109]:
# attribute
x.shape
x.dtype

# shape manipulation
x.reshape(3,1,3)
x.squeeze()

tensor([[ 0, -1, -1],
        [-1, -1, -1],
        [ 0, -1,  0]])

#### 4.Tensor -- Device

In [113]:
# tensors & modules will be computed with CPU
x.to('cpu')
# x.to('cuda')

tensor([[ 0, -1, -1],
        [-1, -1, -1],
        [ 0, -1,  0]])

In [114]:
# Check if your computer has NVIDIA GPU
torch.__version__
torch.cuda.is_available()

'1.10.0+cpu'

## Deep neuron network

#### 1. Dataset & Dataloader

In [ ]:
from torch.utils.data import Dataset, DataLoader

In [137]:
class myDataset(Dataset):
    def __init__(self):
        self.data = "abcdefghijklmnopqrstuvwxyz"
    
    def __getitem__(self,idx):
        return self.data[idx]
    
    def __len__(self):
        return len(self.data)

# create the dataset
dataset1 = myDataset()
dataloader = DataLoader(dataset=dataset1,shuffle=True,batch_size=2)
for datapoint in dataloader:
    print(datapoint)

['r', 'v']
['p', 'd']
['e', 'b']
['t', 'i']
['n', 'q']
['l', 'j']
['w', 'c']
['s', 'o']
['y', 'k']
['x', 'm']
['f', 'z']
['g', 'u']
['a', 'h']


#### 2. Model —— Build your own neural network 

##### Neural Network

In [2]:
from torch import nn
import torch

In [9]:
## 1. layer
layer = nn.Linear(32,64)
layer.weight.shape
layer.bias.shape

## 2. activation Functions
# nn.ReLU()
# nn.Sigmoid()

tensor([[1, 2],
        [3, 4]])

##### Model

In [8]:
import torch.nn as nn

class MyModel(nn.Module):
    def __init__(self):
        super(MyModel,self).__init__()
        self.net = nn.Sequential(
            nn.Linear(10,32),
            nn.Sigmoid(),
            nn.Linear(32,1)
        )
        
    def forward(self,x):
        return self.net(x)

In [12]:
model = Model()

model.parameters

<bound method Module.parameters of Model(
  (conv1): Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(20, 20, kernel_size=(5, 5), stride=(1, 1))
)>

#### 3. Neural Network Training

In [139]:
# loss Functions 
import torch.nn as nn

nn.MSELoss()
nn.CrossEntropyLoss()

CrossEntropyLoss()

In [140]:
# Optimization algorithms for neural networks (gradient descent)
torch.optim.SGD(params, lr, momentum = 0)

NameError: name 'params' is not defined

In [11]:
import torch.optim as optim

dataset = myDataset()
train_set = DataLoader(dataset,16,shuffle=True)

device = 'cpu'
n_epochs = 100

model = MyModel().to(device)
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), 0.1)

for epoch in range(n_epochs):
    model.train()
    for x, y in train_set:
        optimizer.zero_grad()
        x, y = x.to(device), y.to(device)
        pre = model(x)
        loss = criterion(pre,y)
        loss.backward()
        optimizer.step()                            # update model with optimizer

NameError: name 'myDataset' is not defined

#### 4. Neural Network Evaluation (Validation Set)

In [156]:
model.eval()
total_loss = 0

for x, y in vd_set:
    x, y = x.to(device), y.to(device)
    with torch.no_grad(): # disable gradient calculation
        pre = model(x)
        loss = criterion(pre,y)
    total_loss += loss.cpu().item() * len(x)
    avg_loss = total_loss / len(vd_set.dataset)

NameError: name 'dv_set' is not defined

#### 5. Neural Network Evaluation (Testing Set)

In [ ]:
model.eval()
preds = []

for x in test_set:
    x = x.to(device)
    with torch.no_grad():
        pred = model(x)
    preds.append(pred.cpu())

#### 6. Save/Load a Neural Network

In [ ]:
# Save
torch.save(model.state_dict(), path)

# Load 
ckpt = torch.load(path)
model.load_state_dict(ckpt)

## Common errors



The following code blocks show some common errors while using the torch library. First, execute the code with error, and then execute the next code block to fix the error. You need to change the runtime to GPU.


In [ ]:
import torch

In [13]:
# 1. different device error
model = torch.nn.Linear(5,1).to("cuda:0")
x = torch.Tensor([1,2,3,4,5]).to("cpu")
y = model(x)

In [14]:
# 1. different device error (fixed)
x = torch.Tensor([1,2,3,4,5]).to("cuda:0")
y = model(x)
print(y.shape)

AssertionError: Torch not compiled with CUDA enabled

In [15]:
# 2. mismatched dimensions error
x = torch.randn(4,5)
y= torch.randn(5,4)
z = x + y

RuntimeError: The size of tensor a (5) must match the size of tensor b (4) at non-singleton dimension 1

In [ ]:
# 2. mismatched dimensions error (fixed)
y= y.transpose(0,1)
z = x + y
print(z.shape)

torch.Size([4, 5])


In [2]:
# 3. cuda out of memory error
import torch
import torchvision.models as models
device = 'cpu'

resnet18 = models.resnet18().to(device) # Neural Networks for Image Recognition
data = torch.randn(2048,3,244,244) # Create fake data (512 images)
out = resnet18(data.to(device)) # Use Data as Input and Feed to Model
print(out.shape)

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
  

In [13]:
resnet18.parameters

<bound method Module.parameters of ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)


In [15]:
# 3. cuda out of memory error (fixed)
data = torch.randn(2048,3,244,244) 
for d in data:
    out = resnet18(d.to(device).unsqueeze(0))
    print(out.shape)

torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size

torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size

torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size

torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size

torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size

torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size([1, 1000])
torch.Size

In [24]:
# 4. mismatched tensor type
import torch.nn as nn
L = nn.CrossEntropyLoss()
outs = torch.randn(5,5)
labels = torch.Tensor([1,2,3,4,0])
# lossval = L(outs,labels) # Calculate CrossEntropyLoss between outs and labels
print(labels.long().dtype)
print(out.dtype)

torch.int64
torch.float32


In [31]:
# 4. mismatched tensor type (fixed)
labels = labels.long()
lossval = L(outs,labels)
print(lossval)

tensor(2.2397)
